export default {
  agents: 'AI Agents',
  apps: 'AI Apps',
  basedOnNote: 'Based on Note',
  generate: 'Generate',
  generateDisclaimer: 'Content generated by AI. Please verify carefully.',
  model: 'AI Model',
  models: {
    chat: 'Chat LLM',
    chatModel: 'Chat and Reasoning Model (LLM)',
    chatTips: 'Default chat LLM',
    embedding: 'Embedding',
    embeddingModel: 'Embedding Model',
    rerank: 'Rerank',
    rerankModel: 'Rerank Model',
    stt: 'Speech-to-Text',
    sttModel: 'Speech-to-Text Model',
    system: 'System Model Settings',
    tts: 'Text-to-Speech',
    ttsModel: 'Text-to-Speech Model (TTS)',
    vector: 'Vector Database'
  },
  providers: {
    added: 'Added Providers',
    api: {
      baseUrl: 'Custom API endpoint URL',
      baseUrlGet: 'Get your API Key from {name}',
      baseUrlPlaceholder: 'API Base URL',
      key: 'API Key',
      keyInvalid: 'Your API Key is invalid',
      keys: 'API Keys',
      keyTips: 'Your API KEY will be encrypted and stored using PKCS1_OAEP technology.'
    },
    available: 'Available Providers',
    title: 'Model Providers'
  },
  regenerate: 'Re-generate',
  settings: 'AI Settings'
}
