"""v0.0.2

Revision ID: 2f9840ccfb43
Revises: 4f9c62911e32
Create Date: 2025-11-11 13:32:35.008871

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9840ccfb43'
down_revision: Union[str, None] = '4f9c62911e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_collection', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('book_collection', 'styles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_collection', sa.Column('styles', sa.VARCHAR(), nullable=True))
    op.drop_column('book_collection', 'color')
    # ### end Alembic commands ###
