"""v0.0.2

Revision ID: 58425ce2aebb
Revises: ca2639e13ab2
Create Date: 2025-11-27 11:11:12.209136

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58425ce2aebb'
down_revision: Union[str, None] = 'ca2639e13ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('ref_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('ref_id')
        batch_op.drop_column('ref_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('ref_id', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('ref_type')
        batch_op.drop_column('ref_id')

    # ### end Alembic commands ###
