"""v0.0.3

Revision ID: 847e4561d44f
Revises: 572100f11c82
Create Date: 2025-12-10 23:35:52.341444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847e4561d44f'
down_revision: Union[str, None] = '572100f11c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_book', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_workspace_book'), type_='unique')
        batch_op.create_unique_constraint('unique_workspace_user_book', ['workspace_id', 'book_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_book', schema=None) as batch_op:
        batch_op.drop_constraint('unique_workspace_user_book', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_workspace_book'), ['workspace_id', 'book_id'])

    # ### end Alembic commands ###
