"""v0.0.2

Revision ID: a700246362ab
Revises:
Create Date: 2025-11-12 12:52:19.962288

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision: str = 'a700246362ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('user_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('tenant_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('app_model_config_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('book',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('tenant_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('user_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scope', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('book_annotation',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('tenant_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('user_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('book_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('tenant_book_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chapter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('book_collection',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('tenant_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('user_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('parent', app.api.models.base.UUIDString(length=36), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('file_meta',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('tenant_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('user_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('mimetype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ref_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('note',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('tenant_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('user_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('parent', app.api.models.base.UUIDString(length=36), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('favorite', sa.Integer(), nullable=True),
    sa.Column('styles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ref_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tenant_book',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('tenant_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('book_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('user_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('reading_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reading_percentage', sa.Float(), nullable=True),
    sa.Column('reading_status', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reading_status_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.String(), server_default='[]', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'book_id', name='unique_tenant_book')
    )
    op.create_table('tenant_book_collection',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('tenant_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('book_collection_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('tenant_book_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('tenant_book_id', 'book_collection_id', name='unique_tenant_book_collection')
    )
    op.create_table('tenant_member',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('tenant_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('user_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('invited_by', app.api.models.base.UUIDString(length=36), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_salt', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('settings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_login_time', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('last_login_ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('last_active_time', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('tenant_member')
    op.drop_table('tenant_book_collection')
    op.drop_table('tenant_book')
    op.drop_table('tenant')
    op.drop_table('note')
    op.drop_table('file_meta')
    op.drop_table('book_collection')
    op.drop_table('book_annotation')
    op.drop_table('book')
    op.drop_table('app')
    # ### end Alembic commands ###
