"""v0.0.2

Revision ID: bc48bce2efc2
Revises: c4cb8035f139
Create Date: 2025-11-25 21:19:21.956212

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision: str = 'bc48bce2efc2'
down_revision: Union[str, None] = 'c4cb8035f139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('app_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('model_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('favorite', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('message',
    sa.Column('create_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Created time'),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('app_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('conversation_id', app.api.models.base.UUIDString(length=36), nullable=False),
    sa.Column('model_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_tokens', sa.Integer(), nullable=True),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answer_tokens', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ref_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('app_model_config_id',
               existing_type=sa.CHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('app_model_config_id',
               existing_type=sa.CHAR(length=36),
               nullable=False)

    op.drop_table('message')
    op.drop_table('conversation')
    # ### end Alembic commands ###
