"""v0.0.2

Revision ID: ca2639e13ab2
Revises: bc48bce2efc2
Create Date: 2025-11-26 23:55:23.483377

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2639e13ab2'
down_revision: Union[str, None] = 'bc48bce2efc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('reasoning_content', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('result', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_tokens', sa.Integer(), nullable=True))
        batch_op.drop_column('message_tokens')
        batch_op.drop_column('answer')
        batch_op.drop_column('answer_tokens')
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('answer_tokens', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('answer', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('message_tokens', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_tokens')
        batch_op.drop_column('result')
        batch_op.drop_column('reasoning_content')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
