"""v0.0.3

Revision ID: d9895516cd7e
Revises: 219bf2b442ee
Create Date: 2026-01-30 23:01:06.743313

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9895516cd7e'
down_revision: Union[str, None] = '219bf2b442ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_version', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
