"""v0.6.3

Revision ID: 57dccacf4cba
Revises: 9be3cd376d02
Create Date: 2026-06-15 13:08:54.877495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision: str = '57dccacf4cba'
down_revision: Union[str, None] = '9be3cd376d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', app.api.models.base.JSONString(), nullable=True))

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_edit_by', app.api.models.base.GUID(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), server_default='normal', nullable=False))
        batch_op.alter_column('settings',
               existing_type=sa.VARCHAR(),
               type_=app.api.models.base.JSONString(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', app.api.models.base.JSONString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_book', schema=None) as batch_op:
        batch_op.drop_column('options')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('settings',
               existing_type=app.api.models.base.JSONString(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('role')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('last_edit_by')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('options')

    # ### end Alembic commands ###
