"""v0.7.1

Revision ID: 3b25996c79ee
Revises: dea24696857d
Create Date: 2026-10-01 23:48:11.323554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision: str = '3b25996c79ee'
down_revision: Union[str, None] = 'dea24696857d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', app.api.models.base.JSONString(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', app.api.models.base.JSONString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('extra')

    with op.batch_alter_table('book_annotation', schema=None) as batch_op:
        batch_op.drop_column('extra')

    # ### end Alembic commands ###
