"""v0.7.0

Revision ID: 1c972ceee2b3
Revises: 3a75afb87324
Create Date: 2026-09-03 09:52:28.966390

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision: str = '1c972ceee2b3'
down_revision: Union[str, None] = '3a75afb87324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Created time'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='Updated time'),
    sa.Column('id', app.api.models.base.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apikey_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('extra', app.api.models.base.JSONString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unique_llm_provider_name')
    )
    with op.batch_alter_table('llm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('extra', app.api.models.base.JSONString(), nullable=True))
        batch_op.alter_column('max_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('unique_llm_workspace_provider_model_name'), type_='unique')
        batch_op.create_unique_constraint('unique_llm_provider_model_name', ['provider', 'model_name'])

    with op.batch_alter_table('workspace_llm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('extra', app.api.models.base.JSONString(), nullable=True))
        batch_op.alter_column('max_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('credential_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_llm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential_id', sa.CHAR(length=36), nullable=False))
        batch_op.alter_column('max_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('extra')
        batch_op.drop_column('model_alias')

    with op.batch_alter_table('llm', schema=None) as batch_op:
        batch_op.drop_constraint('unique_llm_provider_model_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_llm_workspace_provider_model_name'), ['provider', 'model_name'])
        batch_op.alter_column('max_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('extra')
        batch_op.drop_column('model_alias')

    op.drop_table('llm_provider')
    # ### end Alembic commands ###
